### ISSUE TITLE
Enhancement idea: Support for alpha-3 and M49 codes

### ISSUE THREAD

**Issue by michallepicki** [Schultzer/cldr_territories#5]
Many APIs are using 3-letter codes instead of 2-letter equivalents. Also, all teritories have their numeric codes (not only teritories like Europe etc).

For starters we can provide these codes in the `info` function but I think it's possible to support all these three code formats everywhere.

**Comment by Schultzer** [comment]
@michallepicki 

as far as I understand CLDR uses the [UN M.49](https://en.wikipedia.org/wiki/UN_M.49) only for `World `, `Continent` and `Subcontinent ` as shown here [Territory Containment UN M.49](https://www.unicode.org/cldr/charts/32/supplemental/territory_containment_un_m_49.html)


For clarification you want to be able to use the [ISO 3166-1 numeric](https://en.wikipedia.org/wiki/ISO_3166-1_numeric) and [ISO 3166-1 alpha-3](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-3)

### Example 

```elixir
iex> Cldr.Territory.from_territory_code(:"826")
{:ok, "United Kingdom"}

iex> Cldr.Territory.from_territory_code(:GBR)
{:ok, "United Kingdom"}
```

### Implementation requirement
To make this work we need to supply that data from [UN M.49](https://unstats.un.org/unsd/methodology/m49/) a full overview can be found
[here](https://unstats.un.org/unsd/methodology/m49/overview/)

because this package doesn't supply any data and only functions all data are supplied by [`ex_cldr`](https://github.com/kipcole9/cldr) then I would like to know what you think about this @kipcole9

**Comment by michallepicki** [comment]
afaik numeric is the same as m.49

**Comment by Schultzer** [comment]
That's my understanding too.

As far as the Implementation goes I think it would be best to figure this one out together with Kip.

We just have to figure out if this data would be useful across the whole `ex_cldr` ecosystem if so this data should properly be handled by `ex_cldr`

**Comment by kipcole9** [comment]
Sorry for the late reply.  My preference is to keep `ex_cldr` just as a data host for CLDR data.  I believe `ex-cldr_territories` would be the better placed to host additional territory data.

Adding the additional ISO data to `ex_cldr` would tie `ex_cldr_territories` for dependencies beyond CLDR data and would likely slow down the opportunity for innovation in `ex_cldr_territories`.

**Comment by Schultzer** [comment]
Thanks @kipcole9 for your feedback.

@michallepicki 
After some consideration,
I don't see it fit into `ex_cldr_territories` for following reasons

- `CLDR` only use the `UN M.49` sporadic
- Changing the `CDLR` data would only add technical debt (So I don't see any reason to add  [`ISO 3166-1 numeric`](https://en.wikipedia.org/wiki/ISO_3166-1_numeric) and [`ISO 3166-1 alpha-3`](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-3) to `info/1` or other functions)

The alternative here is to make a specific module to convert [`ISO 3166-1`](https://en.wikipedia.org/wiki/ISO_3166-1),
there is a full overview of the codes on ISO home page [`here`](https://www.iso.org/obp/ui/#search/code/)

there are also a few package on hex there does the job

- [iso_3166](https://hex.pm/packages/iso_3166)
- [countries_erlang](https://hex.pm/packages/countries_erlang)
- [iso_erlang](https://hex.pm/packages/iso_erlang)
- [countries](https://hex.pm/packages/countries)
